"""esquema inicial

Revision ID: e5c1502cf678
Revises: 
Create Date: 2026-09-15 03:57:58.149076

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5c1502cf678'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acao_comercial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('custo_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('uplift_esperado_pct', sa.Float(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.CheckConstraint('custo_unitario >= 0', name='ck_acao_custo_nao_negativo'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('periodo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.CheckConstraint('data_fim >= data_inicio', name='ck_periodo_ordem'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_inicio', 'data_fim', name='uq_periodo_intervalo')
    )
    op.create_table('parceiro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('origem_categoria', sa.Enum('INFERIDA', 'SUGERIDA_IA', 'MANUAL', name='origemcategoria'), nullable=True),
    sa.Column('status', sa.Enum('ATIVO', 'PROSPECCAO', 'INATIVO', name='statuscomercial'), nullable=False),
    sa.Column('contato', sa.String(length=120), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(categoria_id IS NULL) = (origem_categoria IS NULL)', name='ck_parceiro_categoria_com_origem'),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index('ix_parceiro_nome', 'parceiro', ['nome'], unique=False)
    op.create_table('historico_segmento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parceiro_id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('segmento', sa.Enum('PROSPECCAO', 'RECEM_CHEGADO', 'EM_RISCO', 'TOP', 'EM_ASCENSAO', 'ESTAVEL', name='segmento'), nullable=False),
    sa.Column('calculado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parceiro_id'], ['parceiro.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parceiro_id', 'periodo_id', name='uq_segmento_parceiro_periodo')
    )
    op.create_index('ix_segmento_periodo_segmento', 'historico_segmento', ['periodo_id', 'segmento'], unique=False)
    op.create_table('previsao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parceiro_id', sa.Integer(), nullable=False),
    sa.Column('periodo_base_id', sa.Integer(), nullable=False),
    sa.Column('faturamento_previsto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('probabilidade_queda', sa.Float(), nullable=False),
    sa.Column('modelo_versao', sa.String(length=40), nullable=False),
    sa.Column('gerada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('probabilidade_queda >= 0 AND probabilidade_queda <= 1', name='ck_previsao_probabilidade'),
    sa.ForeignKeyConstraint(['parceiro_id'], ['parceiro.id'], ),
    sa.ForeignKeyConstraint(['periodo_base_id'], ['periodo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parceiro_id', 'periodo_base_id', 'modelo_versao', name='uq_previsao_parceiro_periodo_modelo')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=60), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.Enum('ADMINISTRADOR', 'GESTOR', 'ANALISTA', 'PARCEIRO', name='perfil'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('parceiro_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(perfil = 'PARCEIRO') = (parceiro_id IS NOT NULL)", name='ck_usuario_parceiro_apenas_perfil_parceiro'),
    sa.ForeignKeyConstraint(['parceiro_id'], ['parceiro.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=60), nullable=False),
    sa.Column('detalhes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('origem', sa.String(length=45), nullable=True),
    sa.Column('ocorrido_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auditoria_ocorrido_em', 'auditoria', ['ocorrido_em'], unique=False)
    op.create_table('execucao_otimizador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('modo', sa.Enum('SERIAL', 'CPU_PARALELO', 'GPU', name='modoexecucao'), nullable=False),
    sa.Column('parametros', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('viavel', sa.Boolean(), nullable=False),
    sa.Column('restricao_violada', sa.String(length=120), nullable=True),
    sa.Column('uplift_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('custo_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tempo_ms', sa.Integer(), nullable=False),
    sa.Column('executada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(viavel AND restricao_violada IS NULL) OR (NOT viavel AND restricao_violada IS NOT NULL)', name='ck_execucao_inviavel_tem_motivo'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('importacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('origem', sa.Enum('TEXTO', 'CSV', name='origemimportacao'), nullable=False),
    sa.Column('total_gravado', sa.Integer(), nullable=False),
    sa.Column('total_rejeitado', sa.Integer(), nullable=False),
    sa.Column('enviado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodo.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metrica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parceiro_id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('importacao_id', sa.Integer(), nullable=False),
    sa.Column('faturamento', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pedidos', sa.Integer(), nullable=False),
    sa.Column('projecao', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.CheckConstraint('faturamento >= 0', name='ck_metrica_faturamento_nao_negativo'),
    sa.CheckConstraint('pedidos >= 0', name='ck_metrica_pedidos_nao_negativo'),
    sa.ForeignKeyConstraint(['importacao_id'], ['importacao.id'], ),
    sa.ForeignKeyConstraint(['parceiro_id'], ['parceiro.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parceiro_id', 'periodo_id', name='uq_metrica_parceiro_periodo')
    )
    op.create_index('ix_metrica_periodo_faturamento', 'metrica', ['periodo_id', 'faturamento'], unique=False)
    op.create_table('plano_campanha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execucao_id', sa.Integer(), nullable=False),
    sa.Column('aplicacao_inicio', sa.Date(), nullable=False),
    sa.Column('aplicacao_fim', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['execucao_id'], ['execucao_otimizador.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execucao_id')
    )
    op.create_table('item_plano',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plano_id', sa.Integer(), nullable=False),
    sa.Column('parceiro_id', sa.Integer(), nullable=False),
    sa.Column('acao_id', sa.Integer(), nullable=False),
    sa.Column('uplift_esperado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('custo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['acao_id'], ['acao_comercial.id'], ),
    sa.ForeignKeyConstraint(['parceiro_id'], ['parceiro.id'], ),
    sa.ForeignKeyConstraint(['plano_id'], ['plano_campanha.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plano_id', 'parceiro_id', name='uq_item_plano_parceiro')
    )
    op.create_table('mensagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parceiro_id', sa.Integer(), nullable=False),
    sa.Column('item_plano_id', sa.Integer(), nullable=True),
    sa.Column('texto_gerado', sa.Text(), nullable=False),
    sa.Column('texto_final', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('PENDENTE', 'APROVADA', 'REJEITADA', name='estadomensagem'), nullable=False),
    sa.Column('decidida_por_id', sa.Integer(), nullable=True),
    sa.Column('motivo_rejeicao', sa.String(length=240), nullable=True),
    sa.Column('gerada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decidida_em', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(estado = 'PENDENTE' AND decidida_por_id IS NULL AND decidida_em IS NULL) OR (estado <> 'PENDENTE' AND decidida_por_id IS NOT NULL AND decidida_em IS NOT NULL)", name='ck_mensagem_decisao_tem_autor'),
    sa.ForeignKeyConstraint(['decidida_por_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['item_plano_id'], ['item_plano.id'], ),
    sa.ForeignKeyConstraint(['parceiro_id'], ['parceiro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mensagem_estado', 'mensagem', ['estado'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mensagem_estado', table_name='mensagem')
    op.drop_table('mensagem')
    op.drop_table('item_plano')
    op.drop_table('plano_campanha')
    op.drop_index('ix_metrica_periodo_faturamento', table_name='metrica')
    op.drop_table('metrica')
    op.drop_table('importacao')
    op.drop_table('execucao_otimizador')
    op.drop_index('ix_auditoria_ocorrido_em', table_name='auditoria')
    op.drop_table('auditoria')
    op.drop_table('usuario')
    op.drop_table('previsao')
    op.drop_index('ix_segmento_periodo_segmento', table_name='historico_segmento')
    op.drop_table('historico_segmento')
    op.drop_index('ix_parceiro_nome', table_name='parceiro')
    op.drop_table('parceiro')
    op.drop_table('periodo')
    op.drop_table('categoria')
    op.drop_table('acao_comercial')
    # ### end Alembic commands ###

    # O autogenerate não remove os tipos ENUM: ele só derruba as tabelas. Sem
    # isto, reverter e reaplicar falha com "type already exists" — e o erro só
    # aparece na segunda execução, quando alguém já perdeu tempo procurando.
    for tipo in (
        'estadomensagem', 'modoexecucao', 'origemimportacao',
        'statuscomercial', 'origemcategoria', 'segmento', 'perfil',
    ):
        op.execute(f'DROP TYPE IF EXISTS {tipo}')
